 console.log(String(123))
 console.log(String(-12.3))
 console.log(String(null))
 console.log(String(undefined))
 console.log(String(true))
 console.log(String(false))

// console.log(Boolean
console.log()
 console.log(Boolean(''))
 console.log(Boolean('Hello'))
 console.log(Boolean(0))
 console.log(Boolean(200))
 console.log(Boolean(-0))
 console.log(Boolean(-200))
 console.log(Boolean(NaN))
 console.log(Boolean(null))
 console.log(Boolean(undefined))
 console.log(Boolean(false))

// console.log(Number
console.log()
 console.log(Number(null))
 console.log(Number(undefined))
 console.log(Number(true))
 console.log(Number(false))
 console.log(Number(" 12 "))
 console.log(Number("-12.34"))
 console.log(Number("\n"))
 console.log(Number(" 12s "))
 console.log(Number(123))
